### ISSUE TITLE
Option to show %

### ISSUE THREAD

**Issue by Resseguie** [dtex/barcli#3]
Would it make sense to have an option to specify that the bar is a percentage? Defines inputRange as [0,100] and adds '%' at the end of the displayed raw value.

**Comment by dtex** [comment]
I don't think we'd need to redefine the range. We could just give the user the option to change the display value to be a percentage of the range.

**Comment by Resseguie** [comment]
Guess not. Might be strange to have a percentage not 0-100 but it's up to them to define what they want, I suppose.

**Comment by dtex** [comment]
I didn't explain myself very well. Examples are better:

What you proposed (as I understand it):

```
var foo = new Barcli({
  range: [0, 100],
  percent: true // option I just made up
};

foo.update(60);

/*
Would give us:
Sensor 1: |***********************                  | 60%
*/
```

I think we should allow any range and map the input value as a percentage of the range:

```
var foo = new Barcli({
  range: [0, 5],
  percent: true
};

foo.update(3);

/*
Would give us:
Sensor 1: |***********************                  | 60%
*/
```

**Comment by Resseguie** [comment]
Oh, yeah, I agree then.

And if a value > range[1] is provided, show 101% (or whatever) in red just like out of bounds values? Less than range[0]? Caluclate negative %?

**Comment by dtex** [comment]
Yes depending on the configuration display one of the following in red:

"> 100%"
"> " + range[1]
"< 0%"
"< " + range[0]

**Comment by dtex** [comment]
Added with 36bf0711e1db9253ae7f1ca2772c444f2a1b2b98
