### ISSUE TITLE
bars aren't drawing correctly with regards to their values

### ISSUE THREAD

**Issue by lirantal** [dtex/barcli#7]
Hi Donovan,

Incase you are still maintaining it - any ideas why the visual bars aren't drawing correctly according to their values?

Example:
![image](https://cloud.githubusercontent.com/assets/316371/24320651/8faaf32e-114a-11e7-99db-0e52e0bc6135.png)

**Comment by dtex** [comment]
Definitely still maintaining, I just don't get many reports of issues. Is it possible to get your code do I can reproduce?

**Comment by lirantal** [comment]
Great to hear :)

I don't have the whole code with barcli but take a look in this gist https://gist.github.com/lirantal/f3f805117e32e6f9a6f311f031d402b9 what I remember doing is inside the `licenseSummary` event I initialized the graphs, something like:
```
for (let license in data.licenses) {
var graph = new Barcli({
  label: license
  range: [0, data.maxLicense.count],
});

graph.update(data.licenses[license]);
}
```

Apologies for the formatting, im replying from mobile.

**Comment by dtex** [comment]
With this code:
````js
'use strict'

const LicenseWatch = require('licensewatch')
const blessed = require('blessed')
const blessedContrib = require('blessed-contrib')
const fs = require('fs')
const Barcli = require('barcli')

const licenses = new LicenseWatch(getModulesDirectory())
licenses.fetch()

licenses.on('licensesSummary', (data) => {
  for (let license in data.licenses) {
    var graph = new Barcli({
      label: license,
      range: [0, data.maxLicense.count],
    });
    graph.update(data.licenses[license])
  }
})

function getModulesDirectory() {
  return process.cwd() + '/node_modules/**/package.json'
}
````
I get:
![Barcli Output](http://www.brandextract.com/images/lw.png)

Not sure why the BSD-2-Clause isn't rendering... looking into it.

**Comment by dtex** [comment]
I've identified the problem and am working on a fix. As labels grow in length the "total space" used to calculate bar length gets smaller. It's never come up because barcli is usually used for dynamic graphs that update constantly (i.e. reading sensor data) and it's only wrong on first update.

**Comment by lirantal** [comment]
awesome, thanks! :)

**Comment by dtex** [comment]
Hi @lirantal, thanks for your patience. v0.0.24 fixes this. It's available on npm now.
